# Generated by Django 3.2.5 on 2021-08-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreeCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=3000)),
                ('headline', models.CharField(max_length=3000)),
                ('days_left', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=1000)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('sub_category', models.CharField(blank=True, max_length=200)),
                ('image_name', models.CharField(blank=True, max_length=200)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('image_file', models.ImageField(blank=True, upload_to='images')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
