# Generated by Django 3.2.5 on 2021-08-15 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freecourses',
            old_name='image_file',
            new_name='image_f',
        ),
    ]
