# Generated by Django 3.2.5 on 2021-08-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_rename_image_file_freecourses_image_f'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freecourses',
            old_name='image_f',
            new_name='image_file',
        ),
    ]
