# Generated by Django 3.2.5 on 2021-08-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0006_rename_image_real_freecourses_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freecourses',
            name='image_file',
            field=models.ImageField(upload_to='images'),
        ),
    ]
