# Generated by Django 3.2.5 on 2021-08-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0009_auto_20210821_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freecourses',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='freecourses',
            name='image_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='freecourses',
            name='link',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='freecourses',
            name='sub_category',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
