# Generated by Django 3.2.5 on 2021-08-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0010_auto_20210821_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freecourses',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
