# Generated by Django 3.2.5 on 2021-08-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0014_auto_20210823_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freecourses',
            options={'ordering': ['date_created']},
        ),
    ]
