# Generated by Django 3.2.5 on 2021-08-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0016_alter_freecourses_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freecourses',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
