# Generated by Django 3.2.5 on 2021-08-27 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0017_alter_freecourses_image_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freecourses',
            options={'ordering': ['-date_created']},
        ),
    ]
